//! EvidenceLog - Issue 4.2
//! First-class harness output providing complete event ledger of all tool calls and decisions

use crate::harness::{
    edit_protocol::EditOperation,
    failure::FailureKind,
    git_checkpoint::GitCheckpoint,
    patch_applier::{PatchResult, RollbackHandle},
    risk::{RiskAssessment, RiskLevel},
    sandbox::SandboxRuntimeKind,
    validation::{CommandResult, ValidationResult},
};
use anyhow::Result;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

/// P0-Issue1: Real sandbox evidence for autonomous mode safety
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxEvidence {
    pub runtime_kind: SandboxRuntimeKind,
    pub isolated_process: bool,
    pub isolated_filesystem: bool,
    pub network_disabled: bool,
    pub cpu_limited: bool,
    pub memory_limited: bool,
    pub container_id: Option<String>,
    pub mount_mode: SandboxMountMode,
    pub resource_limits_applied: bool,
    pub no_new_privileges: bool,
    pub capabilities_dropped: bool,
    pub seccomp_enabled: bool,
    // P0-Audit-005: Additional hardening evidence fields
    pub pids_limit: Option<u32>,
    pub non_root_user: bool,
    pub tmpfs_protected: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum SandboxMountMode {
    ReadOnly,
    ReadWrite,
}

/// Types of evidence entries for the execution ledger
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum EvidenceEntryKind {
    /// Repository context was built
    RepoMapBuilt,
    /// Patch was generated by provider
    PatchGenerated,
    /// Dry-run verification passed
    DryRunPassed,
    /// Dry-run verification failed
    DryRunFailed,
    /// Review completed
    ReviewCompleted,
    /// Risk assessment performed
    RiskAssessed,
    /// Git checkpoint created
    CheckpointCreated,
    /// Patch applied to real repository
    PatchApplied,
    /// Patch applied to temp workspace
    PatchAppliedToTemp,
    /// Validation command run
    ValidationCommandRun,
    /// Validation completed
    ValidationCompleted,
    /// Rollback performed
    RollbackPerformed,
    /// Completion evaluated
    CompletionEvaluated,
    /// Side effect blocked
    SideEffectBlocked,
    /// P0-C3: Sandbox backend used for execution
    SandboxBackendUsed,
    /// User approval requested
    ApprovalRequested,
    /// User approval granted
    ApprovalGranted,
    /// User approval denied
    ApprovalDenied,
    /// Attempt pool candidate result
    AttemptPoolResult,
    /// P2-011: Repair loop started
    RepairLoopStarted,
    /// P2-011: Repair strategy selected
    RepairStrategySelected,
    /// P2-011: Repair edits generated
    RepairEditsGenerated,
    /// P2-011: Repair dry-run result
    RepairDryRunResult,
    /// P2-011: Repair validation result
    RepairValidationResult,
    /// P2-011: Repair completed successfully
    RepairCompleted,
    /// P2-011: Repair failed after max attempts
    RepairFailed,
    /// P1-5.1: Tracing events converted to evidence
    RepositoryContextBuilt,
    ProviderAutoResolved,
    ProviderResolutionFailed,
    FileSetLimitsChecked,
    TempWorkspaceCreated,
    SandboxRuntimeCreated,
    ValidationCommandStarted,
    ValidationCommandCompleted,
    CacheInvalidated,
    SymbolExtractionCompleted,
    DependencyGraphParsed,
    AttemptPoolCandidateEvaluated,
    RepairStrategyApplied,
    ConfigurationLoaded,
}

/// A single entry in the evidence log
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct EvidenceEntry {
    /// Unique identifier for this entry
    pub id: String,
    /// Timestamp when the entry was created
    pub timestamp: DateTime<Utc>,
    /// Type of evidence
    pub kind: EvidenceEntryKind,
    /// Human-readable description
    pub description: String,
    /// Input summary (what went into the decision/action)
    pub input_summary: HashMap<String, String>,
    /// Output summary (what came out of the decision/action)
    pub output_summary: HashMap<String, String>,
    /// Command that was run (if applicable)
    pub command: Option<String>,
    /// Command result (if applicable)
    pub command_result: Option<CommandResult>,
    /// Files that were touched
    pub files_touched: Vec<PathBuf>,
    /// Trace/span ID for observability correlation
    pub trace_id: Option<String>,
    /// Span ID for observability correlation
    pub span_id: Option<String>,
    /// Duration in milliseconds
    pub duration_ms: u64,
    /// Whether this entry represents a successful operation
    pub success: bool,
}

/// Complete evidence log for a harness execution
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct EvidenceLog {
    pub entries: Vec<EvidenceEntry>,
    pub execution_id: String,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
}

impl EvidenceLog {
    /// Create a new evidence log
    pub fn new(execution_id: impl Into<String>) -> Self {
        Self {
            entries: Vec::new(),
            execution_id: execution_id.into(),
            started_at: Some(Utc::now()),
            completed_at: None,
        }
    }

    /// Add an entry to the log
    pub fn add_entry(&mut self, entry: EvidenceEntry) {
        self.entries.push(entry);
    }

    /// Record that repository context was built
    pub fn record_repo_map_built(
        &mut self,
        files_found: usize,
        symbols_found: usize,
        duration_ms: u64,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_repo_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::RepoMapBuilt,
            description: format!("Repository analysis complete: {} files, {} symbols", files_found, symbols_found),
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("files_found".to_string(), files_found.to_string());
                map.insert("symbols_found".to_string(), symbols_found.to_string());
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record that a patch was generated
    pub fn record_patch_generated(
        &mut self,
        source: impl Into<String>,
        edits_count: usize,
        confidence: f32,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_gen_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::PatchGenerated,
            description: format!("Patch generated from {} with {} edits", source.into(), edits_count),
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("edits_count".to_string(), edits_count.to_string());
                map.insert("confidence".to_string(), format!("{:.2}", confidence));
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record dry-run result
    pub fn record_dry_run(&mut self, patch_result: &PatchResult, duration_ms: u64, trace_id: Option<String>) -> EvidenceEntry {
        let success = patch_result.failures.is_empty();
        let entry = EvidenceEntry {
            id: format!("{}_dry_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: if success { EvidenceEntryKind::DryRunPassed } else { EvidenceEntryKind::DryRunFailed },
            description: if success {
                "Dry-run verification passed".to_string()
            } else {
                format!("Dry-run failed: {} failures", patch_result.failures.len())
            },
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("changed_files".to_string(), patch_result.changed_files.len().to_string());
                map.insert("failures".to_string(), patch_result.failures.len().to_string());
                map
            },
            command: None,
            command_result: None,
            files_touched: patch_result.changed_files.clone(),
            trace_id,
            span_id: None,
            duration_ms,
            success,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record risk assessment
    pub fn record_risk_assessed(&mut self, risk: &RiskAssessment, trace_id: Option<String>) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_risk_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::RiskAssessed,
            description: format!("Risk assessment: {:?}", risk.level),
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("risk_level".to_string(), format!("{:?}", risk.level));
                map.insert("requires_approval".to_string(), risk.requires_approval.to_string());
                map.insert("reasons_count".to_string(), risk.reasons.len().to_string());
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record checkpoint creation
    pub fn record_checkpoint_created(&mut self, checkpoint: &GitCheckpoint, trace_id: Option<String>) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_checkpoint_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::CheckpointCreated,
            description: format!("Git checkpoint created: {}", checkpoint.branch_name),
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("branch".to_string(), checkpoint.branch_name.clone());
                map.insert("checkpoint_id".to_string(), checkpoint.id.clone());
                map.insert("committed".to_string(), checkpoint.committed.to_string());
                map
            },
            command: Some("git checkout -b".to_string()),
            command_result: None,
            files_touched: checkpoint.dirty_files.clone(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record patch application
    pub fn record_patch_applied(
        &mut self,
        patch_result: &PatchResult,
        to_temp_workspace: bool,
        rollback_handle: Option<&RollbackHandle>,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_apply_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: if to_temp_workspace { EvidenceEntryKind::PatchAppliedToTemp } else { EvidenceEntryKind::PatchApplied },
            description: if to_temp_workspace {
                "Patch applied to temp workspace".to_string()
            } else {
                format!("Patch applied to real repo with rollback: {}", rollback_handle.is_some())
            },
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("changed_files".to_string(), patch_result.changed_files.len().to_string());
                map.insert("applied".to_string(), patch_result.applied.to_string());
                map.insert("has_rollback".to_string(), rollback_handle.is_some().to_string());
                map
            },
            command: None,
            command_result: None,
            files_touched: patch_result.changed_files.clone(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: patch_result.applied,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record validation command run
    pub fn record_validation_command(&mut self, result: &CommandResult, trace_id: Option<String>) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_valcmd_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::ValidationCommandRun,
            description: format!("Validation command: {} (exit: {:?})", result.command, result.exit_code),
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("exit_code".to_string(), format!("{:?}", result.exit_code));
                map.insert("duration_ms".to_string(), result.duration_ms.to_string());
                map.insert("timed_out".to_string(), result.timed_out.to_string());
                map
            },
            command: Some(result.command.clone()),
            command_result: Some(result.clone()),
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: result.duration_ms,
            success: result.exit_code == Some(0),
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record validation completion
    pub fn record_validation_completed(&mut self, validation: &ValidationResult, trace_id: Option<String>) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_val_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::ValidationCompleted,
            description: format!("Validation completed: {}", if validation.passed() { "PASSED" } else { "FAILED" }),
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("passed".to_string(), validation.passed().to_string());
                map.insert("commands_run".to_string(), validation.command_results.len().to_string());
                map.insert("errors".to_string(), validation.errors.len().to_string());
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: validation.duration_ms,
            success: validation.passed(),
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record rollback
    pub fn record_rollback(&mut self, reason: impl Into<String>, trace_id: Option<String>) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_rollback_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::RollbackPerformed,
            description: format!("Rollback performed: {}", reason.into()),
            input_summary: HashMap::new(),
            output_summary: HashMap::new(),
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record completion evaluation
    pub fn record_completion_evaluated(
        &mut self,
        completion_status: impl Into<String>,
        passed_validation: bool,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_complete_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::CompletionEvaluated,
            description: format!("Completion evaluation: {}", completion_status.into()),
            input_summary: HashMap::new(),
            output_summary: {
                let mut map = HashMap::new();
                map.insert("passed_validation".to_string(), passed_validation.to_string());
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: passed_validation,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record side effect blocked
    pub fn record_side_effect_blocked(
        &mut self,
        reason: impl Into<String>,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_blocked_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::SideEffectBlocked,
            description: format!("Side effect blocked: {}", reason.into()),
            input_summary: HashMap::new(),
            output_summary: HashMap::new(),
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: false,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// P2-011: Record a repair loop action
    pub fn record_repair_action(
        &mut self,
        action: impl Into<String>,
        status: impl Into<String>,
        description: impl Into<String>,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_repair_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::RepairLoopStarted, // Generic kind for repair actions
            description: description.into(),
            input_summary: {
                let mut map = HashMap::new();
                map.insert("action".to_string(), action.into());
                map
            },
            output_summary: {
                let mut map = HashMap::new();
                map.insert("status".to_string(), status.into());
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Record attempt pool result
    pub fn record_attempt_pool_result(
        &mut self,
        attempt_id: &str,
        score: f32,
        passed: bool,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_attempt_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::AttemptPoolResult,
            description: format!("Attempt {} scored {:.2} - {}", attempt_id, score, if passed { "PASSED" } else { "FAILED" }),
            input_summary: {
                let mut map = HashMap::new();
                map.insert("attempt_id".to_string(), attempt_id.to_string());
                map
            },
            output_summary: {
                let mut map = HashMap::new();
                map.insert("score".to_string(), format!("{:.2}", score));
                map.insert("passed".to_string(), passed.to_string());
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: passed,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// P0-C3: Record sandbox backend used for execution
    pub fn record_sandbox_backend_used(
        &mut self,
        backend_type: impl Into<String>,
        backend_details: impl Into<String>,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let backend_type_str = backend_type.into();
        let backend_details_str = backend_details.into();
        
        let entry = EvidenceEntry {
            id: format!("{}_sandbox_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::SandboxBackendUsed,
            description: format!("Sandbox backend used: {}", backend_type_str),
            input_summary: {
                let mut map = HashMap::new();
                map.insert("backend_type".to_string(), backend_type_str);
                map
            },
            output_summary: {
                let mut map = HashMap::new();
                map.insert("backend_details".to_string(), backend_details_str);
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// P0-Issue1: Record detailed sandbox evidence for autonomous mode safety
    pub fn record_sandbox_evidence(
        &mut self,
        evidence: &SandboxEvidence,
        command: Option<&str>,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_sandbox_evidence_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::SandboxBackendUsed,
            description: format!("Sandbox execution: {:?} - process: {}, filesystem: {}, network: {}", 
                evidence.runtime_kind, evidence.isolated_process, evidence.isolated_filesystem, evidence.network_disabled),
            input_summary: {
                let mut map = HashMap::new();
                map.insert("runtime_kind".to_string(), format!("{:?}", evidence.runtime_kind));
                map.insert("isolated_process".to_string(), evidence.isolated_process.to_string());
                map.insert("isolated_filesystem".to_string(), evidence.isolated_filesystem.to_string());
                map.insert("network_disabled".to_string(), evidence.network_disabled.to_string());
                map.insert("cpu_limited".to_string(), evidence.cpu_limited.to_string());
                map.insert("memory_limited".to_string(), evidence.memory_limited.to_string());
                map.insert("resource_limits_applied".to_string(), evidence.resource_limits_applied.to_string());
                map.insert("no_new_privileges".to_string(), evidence.no_new_privileges.to_string());
                map.insert("capabilities_dropped".to_string(), evidence.capabilities_dropped.to_string());
                map.insert("seccomp_enabled".to_string(), evidence.seccomp_enabled.to_string());
                map.insert("mount_mode".to_string(), format!("{:?}", evidence.mount_mode));
                if let Some(ref container_id) = evidence.container_id {
                    map.insert("container_id".to_string(), container_id.clone());
                }
                map
            },
            output_summary: HashMap::new(),
            command: command.map(|c| c.to_string()),
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: true,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// P0-Issue2.1: Record validation command execution counters
    pub fn record_validation_command_counters(
        &mut self,
        commands_planned: usize,
        commands_executed: usize,
        commands_skipped: usize,
        categories_executed: Vec<crate::harness::validation::ValidationCategory>,
        trace_id: Option<String>,
    ) -> EvidenceEntry {
        let entry = EvidenceEntry {
            id: format!("{}_val_counters_{}", self.execution_id, self.entries.len()),
            timestamp: Utc::now(),
            kind: EvidenceEntryKind::ValidationCompleted,
            description: format!(
                "Validation command counters: {} planned, {} executed, {} skipped, {} categories",
                commands_planned, commands_executed, commands_skipped, categories_executed.len()
            ),
            input_summary: {
                let mut map = HashMap::new();
                map.insert("commands_planned".to_string(), commands_planned.to_string());
                map.insert("commands_executed".to_string(), commands_executed.to_string());
                map.insert("commands_skipped".to_string(), commands_skipped.to_string());
                map.insert("categories_count".to_string(), categories_executed.len().to_string());
                map
            },
            output_summary: {
                let mut map = HashMap::new();
                for (i, category) in categories_executed.iter().enumerate() {
                    map.insert(format!("category_{}", i), format!("{:?}", category));
                }
                map
            },
            command: None,
            command_result: None,
            files_touched: Vec::new(),
            trace_id,
            span_id: None,
            duration_ms: 0,
            success: commands_executed > 0,
        };
        self.add_entry(entry.clone());
        entry
    }

    /// Get all entries of a specific kind
    pub fn entries_of_kind(&self, kind: EvidenceEntryKind) -> Vec<&EvidenceEntry> {
        self.entries.iter().filter(|e| e.kind == kind).collect()
    }

    /// Check if there were any failures
    pub fn has_failures(&self) -> bool {
        self.entries.iter().any(|e| !e.success)
    }

    /// Export to JSON
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Mark execution as complete
    pub fn complete(&mut self) {
        self.completed_at = Some(Utc::now());
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_evidence_log_creation() {
        let log = EvidenceLog::new("test_exec");
        assert_eq!(log.execution_id, "test_exec");
        assert!(log.started_at.is_some());
        assert!(log.entries.is_empty());
    }

    #[test]
    fn test_record_repo_map() {
        let mut log = EvidenceLog::new("test");
        let entry = log.record_repo_map_built(10, 50, 100, Some("trace-123".into()));
        assert_eq!(entry.kind, EvidenceEntryKind::RepoMapBuilt);
        assert!(entry.success);
        assert_eq!(entry.trace_id, Some("trace-123".into()));
        assert_eq!(log.entries.len(), 1);
    }

    #[test]
    fn test_entries_of_kind() {
        let mut log = EvidenceLog::new("test");
        log.record_repo_map_built(10, 50, 100, None);
        log.record_repo_map_built(20, 100, 200, None);

        let repo_entries = log.entries_of_kind(EvidenceEntryKind::RepoMapBuilt);
        assert_eq!(repo_entries.len(), 2);
    }

    #[test]
    fn test_has_failures() {
        let mut log = EvidenceLog::new("test");
        assert!(!log.has_failures());

        log.record_side_effect_blocked("test", None);
        assert!(log.has_failures());
    }
}
