pub mod acceptance;
pub mod artifacts;
pub mod completion;
pub mod confidence;
pub mod edit_protocol;
pub mod environment;
pub mod execution_loop;
pub mod failure;
pub mod file_control;
pub mod git_checkpoint;
pub mod patch_applier;
pub mod repo_intelligence;
pub mod review;
pub mod risk;
pub mod sandbox;
pub mod semantic_diff;
pub mod trajectory;
pub mod validation;
pub mod verification;
pub mod work_integration;
pub use artifacts::{HarnessArtifact, generate_completion_artifact};
pub use completion::{CompletionDecision, CompletionEvidence, evaluate_completion};
pub use confidence::{ConfidenceScore, compute_confidence};
pub use edit_protocol::*;
pub use environment::*;
pub use execution_loop::*;
pub use failure::FailureKind;
pub use file_control::*;
pub use patch_applier::*;
pub use repo_intelligence::*;
pub use risk::*;
pub use sandbox::*;
pub use validation::*;
pub use verification::VerificationStrength;
pub use work_integration::HarnessWorkContextService;
