pub mod acceptance;
pub mod adversarial_validation;
pub mod artifacts;
pub mod completion;
pub mod confidence;
pub mod edit_protocol;
pub mod environment;
pub mod execution_loop;
pub mod failure;
pub mod file_control;
pub mod git_checkpoint;
pub mod knowledge_cache;
pub mod patch_applier;
pub mod repo_intelligence;
pub mod repair_loop;
pub mod reproduction;
pub mod review;
pub mod risk;
pub mod sandbox;
pub mod semantic_diff;
pub mod trajectory;
pub mod validation;
pub mod verification;
pub mod work_integration;

pub use acceptance::{AcceptanceCriterion, compile_acceptance_criteria, compile_acceptance_criteria_with_env, get_verification_summary, update_criterion_status, AcceptanceCompiler, CompiledAcceptanceCriteria, CriterionPriority, CriterionStatus, VerificationMethod};
pub use adversarial_validation::{generate_adversarial_tests, AdversarialTestSuite, EdgeCaseTest, PropertyTest, EdgeCaseType, Property, TestPriority};
pub use artifacts::{HarnessArtifact, generate_completion_artifact};
pub use completion::{CompletionDecision, CompletionEvidence, evaluate_completion};
pub use confidence::{ConfidenceScore, compute_confidence, ConfidenceFactor, ConfidenceCalibrator, ConfidenceWeights, FactorImpact, ConfidenceClassification};
pub use edit_protocol::*;
pub use environment::*;
pub use execution_loop::*;
pub use failure::{FailureKind, FailureDetails, FailureContext, FailureCategory, classify_patch_failure, classify_validation_failure, classify_command_failure, analyze_failure_pattern, create_failure_details, format_failure_report};
pub use git_checkpoint::{GitCheckpoint, GitCheckpointManager, RollbackStrategy, is_git_repo, get_repo_info, RepoInfo};
pub use knowledge_cache::{TaskLocalKnowledgeCache, KnowledgeCacheManager, CacheScope, CacheValue, CacheKey};
pub use repair_loop::{RepairLoop, RepairRequest, RepairResult, RepairAttempt, RepairStrategy, run_repair_loop, format_repair_report};
pub use reproduction::{generate_reproduction_test, ReproductionRequest, ReproductionResult, ReproductionMode, FixType};
pub use review::{ReviewIssue, ReviewIssueType, ReviewSeverity, ReviewReport, ReviewEngine, generate_review_report, format_review_report, has_critical_issues, review_diff, review_file};
pub use risk::{RiskAssessment, RiskLevel, RiskCategory, RiskReason, RiskEngine, OverridePolicy, OverrideResult, assess_risk, format_risk_assessment};
pub use semantic_diff::{analyze_semantic_diff, SemanticDiff, ApiChange, AuthChange, DatabaseChange, DependencyChange, RiskLevel as SemanticRiskLevel, has_breaking_changes, requires_approval};
pub use file_control::*;
pub use patch_applier::*;
pub use repo_intelligence::*;
pub use sandbox::*;
pub use validation::*;
pub use verification::{VerificationStrength, VerificationAssessment, VerificationLevel, assess_verification_strength, format_verification_assessment};
pub use work_integration::HarnessWorkContextService;
