// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pebchtczwukueljxtayo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlYmNodGN6d3VrdWVsanh0YXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjU0NzIsImV4cCI6MjA2OTk0MTQ3Mn0.UnwRSZvmO9BnJaoXuh50XF_1QHY0-P-v9C8ivxV2Bww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});